#pragma once

#include "command.h"

namespace glmock
{
	//
	// Exception thrown by the framework when one of the OpenGL functions are invoked
	// in an unexpected manner. Such as:
	//
	// 1. Wrong function was called
	// 2. Function that was called had the wrong types of parameters
	// 3. Not all functions specified was invoked
	//
	class DLL_EXPORT IMockException
	{
	public:
		IMockException(CommandError*& const errors, const unsigned int& count);
		virtual ~IMockException() {}

	public:
		// Read-only property containing all the errors
		CommandError*& const Errors;

		// Read-only property containing how many errors where generated by the mock framework
		const unsigned int& Count;
	};

	//
	// 
	class MockException : public IMockException
	{
	public:
		MockException(CommandError* errors, unsigned int count);
		~MockException();

	private:
		CommandError* mErrors;
		unsigned int mCount;
	};
}
