#pragma once

namespace glmock
{
	
#define STRINGIFY(T) const char __STR_##T[] = #T
#define AS_STRING(T) __STR_##T

	STRINGIFY(GL_TEXTURE_1D);
	STRINGIFY(GL_TEXTURE_2D);
	STRINGIFY(GL_TEXTURE_3D);
	STRINGIFY(GL_TEXTURE_1D_ARRAY);
	STRINGIFY(GL_TEXTURE_2D_ARRAY);
	STRINGIFY(GL_TEXTURE_RECTANGLE);
	STRINGIFY(GL_TEXTURE_CUBE_MAP);
	STRINGIFY(GL_TEXTURE_BUFFER);
	STRINGIFY(GL_TEXTURE_2D_MULTISAMPLE);
	STRINGIFY(GL_TEXTURE_2D_MULTISAMPLE_ARRAY);

	STRINGIFY(GL_ZERO);
	STRINGIFY(GL_ONE);
	STRINGIFY(GL_SRC_COLOR);
	STRINGIFY(GL_ONE_MINUS_SRC_COLOR);
	STRINGIFY(GL_DST_COLOR);
	STRINGIFY(GL_ONE_MINUS_DST_COLOR);
	STRINGIFY(GL_SRC_ALPHA);
	STRINGIFY(GL_ONE_MINUS_SRC_ALPHA);
	STRINGIFY(GL_DST_ALPHA);
	STRINGIFY(GL_ONE_MINUS_DST_ALPHA);
	STRINGIFY(GL_CONSTANT_COLOR);
	STRINGIFY(GL_ONE_MINUS_CONSTANT_COLOR);
	STRINGIFY(GL_CONSTANT_ALPHA);
	STRINGIFY(GL_ONE_MINUS_CONSTANT_ALPHA);
	STRINGIFY(GL_SRC_ALPHA_SATURATE);
	STRINGIFY(GL_SRC1_COLOR);
	STRINGIFY(GL_ONE_MINUS_SRC1_COLOR);
	STRINGIFY(GL_SRC1_ALPHA);
	STRINGIFY(GL_ONE_MINUS_SRC1_ALPHA);

	// ERRORS
	
	STRINGIFY(GL_INVALID_ENUM);
	STRINGIFY(GL_INVALID_VALUE);
	STRINGIFY(GL_INVALID_OPERATION);

	// UNKNOWN

	STRINGIFY(UNKNOWN);
}
