#pragma once

#include "../defines.h"

#define STRINGIFY(T) const char __STR_##T[] = #T
#define AS_STRING(T) __STR_##T

namespace glmock
{
	
	STRINGIFY(GL_TEXTURE_1D);
	STRINGIFY(GL_TEXTURE_2D);
	STRINGIFY(GL_TEXTURE_3D);
	STRINGIFY(GL_TEXTURE_1D_ARRAY);
	STRINGIFY(GL_TEXTURE_2D_ARRAY);
	STRINGIFY(GL_TEXTURE_RECTANGLE);
	STRINGIFY(GL_TEXTURE_CUBE_MAP);
	STRINGIFY(GL_TEXTURE_BUFFER);
	STRINGIFY(GL_TEXTURE_2D_MULTISAMPLE);
	STRINGIFY(GL_TEXTURE_2D_MULTISAMPLE_ARRAY);

	STRINGIFY(GL_ZERO);
	STRINGIFY(GL_ONE);
	STRINGIFY(GL_SRC_COLOR);
	STRINGIFY(GL_ONE_MINUS_SRC_COLOR);
	STRINGIFY(GL_DST_COLOR);
	STRINGIFY(GL_ONE_MINUS_DST_COLOR);
	STRINGIFY(GL_SRC_ALPHA);
	STRINGIFY(GL_ONE_MINUS_SRC_ALPHA);
	STRINGIFY(GL_DST_ALPHA);
	STRINGIFY(GL_ONE_MINUS_DST_ALPHA);
	STRINGIFY(GL_CONSTANT_COLOR);
	STRINGIFY(GL_ONE_MINUS_CONSTANT_COLOR);
	STRINGIFY(GL_CONSTANT_ALPHA);
	STRINGIFY(GL_ONE_MINUS_CONSTANT_ALPHA);
	STRINGIFY(GL_SRC_ALPHA_SATURATE);
	STRINGIFY(GL_SRC1_COLOR);
	STRINGIFY(GL_ONE_MINUS_SRC1_COLOR);
	STRINGIFY(GL_SRC1_ALPHA);
	STRINGIFY(GL_ONE_MINUS_SRC1_ALPHA);

	STRINGIFY(GL_TEXTURE_BINDING_2D);

	// TYPES

	STRINGIFY(GL_UNSIGNED_BYTE);
	STRINGIFY(GL_BYTE);
	STRINGIFY(GL_UNSIGNED_SHORT);
	STRINGIFY(GL_SHORT);
	STRINGIFY(GL_UNSIGNED_INT);
	STRINGIFY(GL_INT);
	STRINGIFY(GL_FLOAT);
	STRINGIFY(GL_UNSIGNED_BYTE_3_3_2);
	STRINGIFY(GL_UNSIGNED_BYTE_2_3_3_REV);
	STRINGIFY(GL_UNSIGNED_SHORT_5_6_5);
	STRINGIFY(GL_UNSIGNED_SHORT_5_6_5_REV);
	STRINGIFY(GL_UNSIGNED_SHORT_4_4_4_4);
	STRINGIFY(GL_UNSIGNED_SHORT_4_4_4_4_REV);
	STRINGIFY(GL_UNSIGNED_SHORT_5_5_5_1);
	STRINGIFY(GL_UNSIGNED_SHORT_1_5_5_5_REV);
	STRINGIFY(GL_UNSIGNED_INT_8_8_8_8);
	STRINGIFY(GL_UNSIGNED_INT_8_8_8_8_REV);
	STRINGIFY(GL_UNSIGNED_INT_10_10_10_2);
	STRINGIFY(GL_UNSIGNED_INT_2_10_10_10_REV);

	// FORMATS
	STRINGIFY(GL_RED);
	STRINGIFY(GL_RG);
	STRINGIFY(GL_RGB);
	STRINGIFY(GL_BGR);
	STRINGIFY(GL_RGBA);
	STRINGIFY(GL_BGRA);

	// ERRORS
	
	STRINGIFY(GL_INVALID_ENUM);
	STRINGIFY(GL_INVALID_VALUE);
	STRINGIFY(GL_INVALID_OPERATION);
	STRINGIFY(GL_STACK_OVERFLOW);
	STRINGIFY(GL_STACK_UNDERFLOW);
	STRINGIFY(GL_OUT_OF_MEMORY);

	// UNKNOWN

	STRINGIFY(UNKNOWN);
}
